# Generated by Django 3.1.1 on 2020-09-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_assignment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
