# Generated by Django 3.1.1 on 2020-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_submission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
