# Generated by Django 3.1.1 on 2020-10-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0006_auto_20200930_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
