# Generated by Django 3.1.1 on 2020-10-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
