# Generated by Django 3.1.1 on 2020-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='details',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
