# Generated by Django 3.1.1 on 2020-12-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20201201_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.AddField(
            model_name='submission',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
